export default [
  {
    time: -1, // GameOver
    spawnProbability: 1,
    spawnInterval: 0.05,
    minSpeed: 3,
    maxSpeed: 10,
    amount: 1,
  },
  {
    time: 30,
    spawnProbability: 0.9,
    spawnInterval: 3,
    minSpeed: 0.2,
    maxSpeed: 0.8,
    amount: 1,
  },
  {
    time: 70,
    spawnProbability: 0.5,
    spawnInterval: 3,
    minSpeed: 0.2,
    maxSpeed: 0.8,
    amount: 3,
  },
  {
    time: 120,
    spawnProbability: 0.7,
    spawnInterval: 0.5,
    minSpeed: 0.2,
    maxSpeed: 0.8,
    amount: 4,
  },
  {
    time: 160,
    spawnProbability: 0.9,
    spawnInterval: 0.5,
    minSpeed: 0.2,
    maxSpeed: 0.8,
    amount: 7,
  },
  {
    time: 200,
    spawnProbability: 1,
    spawnInterval: 1,
    minSpeed: 0.2,
    maxSpeed: 0.8,
    amount: 8,
  },
];
